// src/utils/fileGenerators.ts

import { LuminaireReportData, PhotometricData } from '../types/data';

/**
 * Genera el contenido de un archivo .ies (formato IESNA:LM-63-2002).
 */
export function generateIesFileContent(reportData: LuminaireReportData, photometricData: PhotometricData): string {
  const { verticalAngles, horizontalAngles, candelaValues } = photometricData;
  const numVertical = verticalAngles.length;
  const numHorizontal = horizontalAngles.length;

  const formatDate = (date: Date) => date.toISOString().slice(0, 10);
  const disclaimer = "Generated by Sens PWA. Estimated data for preliminary purposes only.";

  let iesString = "IESNA:LM-63-2002\n";
  
  // --- BLOQUE CORREGIDO ---
  iesString += `[TEST] ${reportData.productName || 'Estimated Report'}\n`;
  // [TESTLAB] es nuestro rol como simulador
  iesString += `[TESTLAB] LNS Hong Kong (Estimated Report)\n`;
  // [MANUFAC] es el rol del usuario, leído desde el formulario
  iesString += `[MANUFAC] ${reportData.manufacturer || ''}\n`;
  // --- FIN DEL BLOQUE CORREGIDO ---
  
  iesString += `[ISSUEDATE] ${formatDate(new Date())}\n`;
  iesString += `[LUMINAIRE] ${reportData.luminaireType || 'Estimated Luminaire'}\n`;
  iesString += `[OTHER] ${disclaimer}\n`;
  iesString += "TILT=NONE\n";

  const lumens = reportData.luminousFlux || 0;
  iesString += `1 ${lumens} 1 ${numVertical} ${numHorizontal} 1 2 1 0 0\n`;
  iesString += `1 1 ${reportData.power || 0}\n`;

  const formatArray = (arr: number[]) => arr.map(n => n.toFixed(2)).join(' ');
  iesString += formatArray(verticalAngles) + '\n';
  iesString += formatArray(horizontalAngles) + '\n';

  for (let h = 0; h < numHorizontal; h++) {
    const lineValues: string[] = [];
    for (let v = 0; v < numVertical; v++) {
      lineValues.push((candelaValues[v][h] || 0).toFixed(2));
    }
    iesString += lineValues.join(' ') + '\n';
  }

  return iesString;
}

/**
 * Genera el contenido de un archivo .ldt (EULUMDAT).
 */
export function generateLdtFileContent(reportData: LuminaireReportData, photometricData: PhotometricData): string {
  const { verticalAngles, horizontalAngles, candelaValues } = photometricData;
    const today = new Date().toISOString().slice(0, 10).replace(/-/g, '.');
    let ldt = "";

    // --- LÍNEA CORREGIDA ---
    // La primera línea es el fabricante, que viene del formulario.
    ldt += `${reportData.manufacturer || ''}\n`;
    // --- FIN DE LA LÍNEA CORREGIDA ---

    ldt += `${reportData.luminaireType || 'EULUMDAT file'}\n`;
    ldt += `${reportData.productName || 'Luminaria'}\n`;
    // ... (el resto de la función es correcta y no necesita cambios)
    ldt += `${reportData.productName || 'Numero de producto'}\n`;
    ldt += `report-${today}.ldt\n`;
    ldt += `${today}\n`;
    ldt += `${reportData.dimensions || '1000'}\n`;
    ldt += `${reportData.dimensions || '100'}\n`;
    ldt += `0\n`; ldt += `0\n`; ldt += `0\n`;
    ldt += `0\n`; ldt += `0\n`; ldt += `0\n`; ldt += `0\n`;
    ldt += "1.0\n";
    ldt += `${(reportData.luminousFlux || 1000) / 100}\n`;
    ldt += "100.0\n"; ldt += "1\n";
    ldt += `${horizontalAngles.length}\n`;
    ldt += horizontalAngles.map(a => a.toFixed(2)).join(" ") + "\n";
    ldt += `${verticalAngles.length}\n`;
    ldt += verticalAngles.map(a => a.toFixed(2)).join(" ") + "\n";
    for (let h = 0; h < horizontalAngles.length; h++) {
        for (let v = 0; v < verticalAngles.length; v++) {
            ldt += `${(candelaValues[v][h] || 0).toFixed(4)}\n`;
        }
    }
    return ldt;
}