// src/utils/photometricEstimator.ts

import { EstimatorFormData } from '../components/PhotometricEstimatorForm';

export interface PhotometricData {
  verticalAngles: number[];
  horizontalAngles: number[];
  candelaValues: number[][];
}

export function generateEstimatedPhotometricData(formData: EstimatorFormData): PhotometricData {
  const { luminousFlux, beamAngle, opticsType, emissionShape } = formData;
  const verticalAngles: number[] = [];
  for (let i = 0; i <= 180; i += 2.5) {
    verticalAngles.push(i);
  }
  const horizontalAngles = [0, 90];
  const beamAngleRad = (beamAngle / 2) * (Math.PI / 180);
  const fluxFactor = Math.PI * (1 - Math.cos(beamAngleRad)) || 1;
  const maxIntensity = (luminousFlux || 0) / fluxFactor;
  let n_factor = 1.0;
  switch (opticsType) {
    case 'Lente TIR': n_factor = Math.log(0.5) / Math.log(Math.cos(beamAngleRad)); break;
    case 'Reflector': n_factor = (Math.log(0.5) / Math.log(Math.cos(beamAngleRad))) * 0.8; break;
    case 'Difusor Opal': n_factor = 1; break;
    default: n_factor = Math.log(0.5) / Math.log(Math.cos(beamAngleRad));
  }
  let asymmetryFactor = 1.0;
  switch (emissionShape) {
    case 'Simétrica': asymmetryFactor = 1.0; break;
    case 'Asimétrica': asymmetryFactor = 0.75; break;
    case 'Wallwasher': asymmetryFactor = 0.5; break;
    default: asymmetryFactor = 1.0;
  }
  const calculateIntensity = (angle: number, n: number) => {
    if (angle > 90) return 0;
    const angleRad = angle * (Math.PI / 180);
    return maxIntensity * Math.pow(Math.cos(angleRad), n);
  };
  const candelasC0 = verticalAngles.map(angle => calculateIntensity(angle, n_factor));
  const candelasC90 = verticalAngles.map(angle => calculateIntensity(angle, n_factor / asymmetryFactor));
  const candelaValuesMatrix: number[][] = [];
  for (let i = 0; i < verticalAngles.length; i++) {
    candelaValuesMatrix.push([candelasC0[i], candelasC90[i]]);
  }
  return {
    verticalAngles,
    horizontalAngles,
    candelaValues: candelaValuesMatrix,
  };
}
// src/utils/photometricEstimator.ts

// ... (todo el código que ya tienes de 'generateEstimatedPhotometricData' va aquí arriba) ...


// --- AÑADE ESTA FUNCIÓN COMPLETA AL FINAL DEL ARCHIVO ---

/**
 * Genera el contenido de un archivo .ies en formato string a partir de los datos de la app.
 * @param reportData - Los datos del informe (nombre, fabricante, potencia, etc.).
 * @param photometricData - Los datos de la curva (ángulos y candelas).
 * @returns Un string con el formato completo de un archivo IES listo para ser descargado.
 */
export function generateIesFileContent(
  reportData: any, // Usamos 'any' para flexibilidad, pero se basa en LuminaireReportData
  photometricData: PhotometricData
): string {

  const { verticalAngles, horizontalAngles, candelaValues } = photometricData;
  const numVertical = verticalAngles.length;
  const numHorizontal = horizontalAngles.length;
  
  // Función interna para formatear números
  const formatNumber = (num: number, decimals: number) => num.toFixed(decimals);

  // --- CONSTRUCCIÓN DEL STRING IES ---

  // 1. Cabecera estándar y metadatos
  let iesString = "IESNA:LM-63-2002\n";
  iesString += `[TEST] ${reportData.name || 'Generated Report'}\n`;
  iesString += `[MANUFAC] ${reportData.manufacturer || 'Generated by LNS Tool'}\n`;
  // Puedes añadir más metadatos aquí si los tienes en reportData
  // iesString += `[LUMINAIRE] ${reportData.type || 'Estimated Luminaire'}\n`;
  
  // 2. Línea TILT (siempre NONE para nuestro caso)
  iesString += "TILT=NONE\n";

  // 3. Línea de Propiedades Principales (la más importante)
  const numLamps = reportData.lampsInside || 1;
  // Usamos luminousFlux del formulario, no lampFlux que puede ser un string con 'lm'
  const lumensPerLamp = reportData.luminousFlux || (reportData.nominalFlux || 0);
  const candelaMultiplier = 1;
  const photometricType = 1; // Tipo C (el más común)
  const unitsType = 2; // Unidades métricas (metros)
  const width = 0; // Ancho, largo y alto de la superficie luminosa (0 para punto de luz)
  const length = 0;
  const height = 0;
  
  iesString += `${numLamps} ${lumensPerLamp} ${candelaMultiplier} ${numVertical} ${numHorizontal} ${photometricType} ${unitsType} ${width} ${length} ${height}\n`;

  // 4. Línea de Ballast, Factor de Potencia y Potencia
  const ballastFactor = 1.0;
  const futureUse = 1.0;
  const inputWatts = reportData.power || (reportData.nominalPower || 0);
  iesString += `${ballastFactor} ${futureUse} ${inputWatts}\n`;

  // 5. Lista de Ángulos Verticales
  let verticalAnglesStr = verticalAngles.map(a => formatNumber(a, 2)).join(' ');
  iesString += `${verticalAnglesStr}\n`;

  // 6. Lista de Ángulos Horizontales
  let horizontalAnglesStr = horizontalAngles.map(a => formatNumber(a, 2)).join(' ');
  iesString += `${horizontalAnglesStr}\n`;

  // 7. Lista de Valores de Candelas
  // El formato IES escribe los valores por columnas: todos los valores verticales para el
  // primer ángulo horizontal, luego todos para el segundo, etc.
  let candelaStr = "";
  for (let h = 0; h < numHorizontal; h++) {
    for (let v = 0; v < numVertical; v++) {
      // Nos aseguramos de que el valor no sea negativo o NaN
      const candelaValue = Math.max(0, candelaValues[v][h] || 0);
      candelaStr += `${formatNumber(candelaValue, 2)} `;
    }
  }
  iesString += candelaStr.trim() + "\n";

  return iesString;
}